apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: java-app-build-run-
  namespace: user6-ai-agent
spec:
  taskRunTemplate:
    serviceAccountName: pipeline
  pipelineRef:
    name: java-app-build
  params:
    - name: NAMESPACE
      value: user6-ai-agent
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
